---
- name: Example Local Playbook
  hosts: localhost
  connection: local  # This indicates the playbook should run locally      # Optional, if tasks require elevated privileges

  tasks:
    - name: Run backend service
      command: docker-compose -f ./main/docker-compose.yml up -d backend


